# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-13 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAdvisorCohort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Advisor')),
            ],
        ),
        migrations.RenameField(
            model_name='cohort',
            old_name='description',
            new_name='label',
        ),
        migrations.RemoveField(
            model_name='student',
            name='cohort',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mentor_username',
        ),
        migrations.AddField(
            model_name='studentadvisorcohort',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Cohort'),
        ),
        migrations.AddField(
            model_name='studentadvisorcohort',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='studentadvisorcohort',
            unique_together=set([('student', 'cohort', 'advisor')]),
        ),
    ]
