# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-17 21:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advising', '0020_classsitescore_studentclasssitescore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentclasssitestatus',
            options={'ordering': ('status__order',)},
        ),
    ]
