# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-18 22:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advising', '0021_auto_20160217_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='statuses',
        ),
    ]
