class EventNames(object):
    UserCreated = 'UserCreated'
    UserInviteEmailSent = 'UserInviteEmailSent'
    UserEmailVerified = 'UserEmailVerified'
    UserPasswordChanged = 'UserPasswordChanged'
    UserEmailSent = 'UserEmailSent'
    UserConsented = 'UserConsented'
    UserActivated = 'UserActivated'
    UserWithdrawn = 'UserWithdrawn'
    UserReset = 'UserReset'
    UserLoggedIn = 'UserLoggedIn'
    UserLoggedOut = 'UserLoggedOut'
    PageViewed = 'PageViewed'
    PageError = 'PageError'
    Redirected = 'Redirected'
    Searched = 'Searched'
