# Generated by Django 3.2.12 on 2022-02-10 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'get_latest_by': 'modified'},
        ),
    ]
