# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-01 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('username', models.CharField(max_length=8)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('username', models.CharField(max_length=8)),
                ('univ_id', models.CharField(max_length=11)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='StudentGroupAdvisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisinggroups.Advisor')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisinggroups.Group')),
                ('imp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisinggroups.Import')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisinggroups.Student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='advisors',
            field=models.ManyToManyField(through='advisinggroups.StudentGroupAdvisor', to='advisinggroups.Advisor'),
        ),
        migrations.AddField(
            model_name='student',
            name='groups',
            field=models.ManyToManyField(through='advisinggroups.StudentGroupAdvisor', to='advisinggroups.Group'),
        ),
        migrations.AddField(
            model_name='advisor',
            name='groups',
            field=models.ManyToManyField(through='advisinggroups.StudentGroupAdvisor', to='advisinggroups.Group'),
        ),
        migrations.AddField(
            model_name='advisor',
            name='students',
            field=models.ManyToManyField(through='advisinggroups.StudentGroupAdvisor', to='advisinggroups.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='studentgroupadvisor',
            unique_together=set([('imp', 'student', 'advisor', 'group')]),
        ),
    ]
