# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-31 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=8)),
                ('univ_id', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='StudentGroupAdvisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisinggroups.Advisor')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisinggroups.Group')),
                ('imp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisinggroups.Import')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisinggroups.Student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='advisors',
            field=models.ManyToManyField(through='advisinggroups.StudentGroupAdvisor', to='advisinggroups.Advisor'),
        ),
        migrations.AddField(
            model_name='student',
            name='groups',
            field=models.ManyToManyField(through='advisinggroups.StudentGroupAdvisor', to='advisinggroups.Group'),
        ),
        migrations.AddField(
            model_name='advisor',
            name='students',
            field=models.ManyToManyField(through='advisinggroups.StudentGroupAdvisor', to='advisinggroups.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='studentgroupadvisor',
            unique_together=set([('imp', 'student', 'advisor', 'group')]),
        ),
    ]
