# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-05 17:53


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seumich', '0002_custom_add_composite_primary_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyclasssitescore',
            name='score',
            field=models.FloatField(db_column=b'CLASS_CURR_SCR_AVG'),
        ),
        migrations.AlterField(
            model_name='weeklystudentclasssitescore',
            name='score',
            field=models.FloatField(db_column=b'STDNT_CURR_SCR_AVG'),
        ),
    ]
